version: "3.9"
services:
  gateway:
    image: traefik:latest
    restart: always
    command:
      - --providers.docker
      - --entryPoints.web.address=:8080
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
  frontend:
    image: twaddle/web:latest
    build:
      context: ../
    restart: always
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
